import type { HazardItem } from "./types"

export const mockHazardData: HazardItem[] = [
  {
    id: 1,
    status: "pending",
    date: "2026.05.18",
    location: "3층 계단실",
    description: "계단 난간 파손으로 추락 위험 존재",
    reporterName: "김철수",
    reporterInitial: "김",
    workplace: "광교타워크레인 현장",
    isMyReport: true,
  },
  {
    id: 2,
    status: "ongoing",
    date: "2026.05.16",
    location: "지하 1층 전기실",
    description: "배전반 문 잠금장치 불량, 감전 위험",
    reporterName: "이영희",
    reporterInitial: "이",
    workplace: "광교타워크레인 현장",
    isMyReport: false,
  },
  {
    id: 3,
    status: "completed",
    date: "2026.05.14",
    location: "옥상 작업장",
    description: "안전난간 미설치 구간 발생",
    reporterName: "박민준",
    reporterInitial: "박",
    workplace: "수원역 복합개발 현장",
    isMyReport: true,
  },
  {
    id: 4,
    status: "impossible",
    date: "2026.05.12",
    location: "2층 화장실",
    description: "바닥 미끄럼 방지 타일 탈락",
    reporterName: "최지원",
    reporterInitial: "최",
    workplace: "수원역 복합개발 현장",
    isMyReport: false,
  },
  {
    id: 5,
    status: "pending",
    date: "2026.05.10",
    location: "1층 로비",
    description: "비상구 앞 적재물 방치로 대피 경로 차단",
    reporterName: "정우성",
    reporterInitial: "정",
    workplace: "광교타워크레인 현장",
    isMyReport: true,
  },
  {
    id: 6,
    status: "ongoing",
    date: "2026.05.08",
    location: "외벽 비계",
    description: "비계 연결 볼트 이완, 구조 불안정",
    reporterName: "한수진",
    reporterInitial: "한",
    workplace: "수원역 복합개발 현장",
    isMyReport: false,
  },
]
