import type { ProposalItem } from "./types"

export const mockProposalData: ProposalItem[] = [
  {
    id: 1,
    status: "pending",
    date: "2026.02.23",
    title: "화장실 세면대에 물이 넘치고 있습니다",
    content: "1층 화장실 세면대 배수구가 막혀 물이 넘쳐흐르고 있습니다. 빠른 점검이 필요합니다.",
    authorInitial: "이",
    authorName: "이현수",
    isMyProposal: false,
  },
  {
    id: 2,
    status: "ongoing",
    date: "2026.02.10",
    title: "휴게실 의자 교체 요청",
    content: "휴게실 의자 다수가 파손되어 사용이 불편합니다. 교체를 요청드립니다.",
    authorInitial: "박",
    authorName: "박지훈",
    isMyProposal: false,
  },
  {
    id: 3,
    status: "reflected",
    date: "2026.01.14",
    title: "작업장 조명 개선 요청",
    content: "야간 작업 시 조명이 어두워 안전사고 위험이 있습니다. LED 추가 설치를 건의합니다.",
    authorInitial: "김",
    authorName: "김관리",
    isMyProposal: false,
  },
  {
    id: 4,
    status: "rejected",
    date: "2026.01.09",
    title: "안전모 보관함 추가 설치 요청",
    content: "현재 보관함 수량이 부족해 안전모가 바닥에 방치되는 경우가 많습니다.",
    authorInitial: "최",
    authorName: "최성민",
    isMyProposal: false,
  },
  {
    id: 5,
    status: "pending",
    date: "2026.01.03",
    title: "창고 바닥 미끄럼 방지 패드 요청",
    content: "창고 입구 바닥이 비가 오면 매우 미끄럽습니다. 미끄럼 방지 패드 설치를 요청합니다.",
    authorInitial: "정",
    authorName: "정다은",
    isMyProposal: true,
  },
]
