import type { ProposalItem } from "./types"

export const mockProposalData: ProposalItem[] = [
  {
    id: 1,
    status: "pending",
    date: "2026.02.23",
    title: "화장실 세면대에 물이 넘치고 있습니다",
    content: "1층 화장실 세면대 배수구가 막혀 물이 넘쳐흐르고 있습니다.",
    authorInitial: "홍",
    authorName: "홍길동",
    isMyProposal: true,
  },
  {
    id: 2,
    status: "pending",
    date: "2026.02.20",
    title: "B구역 안전망 탈락 재설치 요청",
    content: "B구역 안전망이 일부 탈락되어 있습니다. 즉시 재설치가 필요합니다.",
    authorInitial: "김",
    authorName: "김민수",
    isMyProposal: false,
  },
  {
    id: 3,
    status: "ongoing",
    date: "2026.02.10",
    title: "휴게실 의자 교체 요청",
    content: "휴게실 의자 다수가 파손되어 사용이 불편합니다. 교체를 요청드립니다.",
    authorInitial: "홍",
    authorName: "홍길동",
    isMyProposal: true,
  },
  {
    id: 4,
    status: "ongoing",
    date: "2026.02.05",
    title: "작업 통로 자재 정리 요청",
    content: "작업 통로에 자재가 쌓여 이동 동선이 막혀 있습니다.",
    authorInitial: "박",
    authorName: "박지훈",
    isMyProposal: false,
  },
  {
    id: 5,
    status: "reflected",
    date: "2026.01.14",
    title: "작업장 조명 개선 요청",
    content: "야간 작업 시 조명이 어두워 안전사고 위험이 있습니다.",
    authorInitial: "홍",
    authorName: "홍길동",
    isMyProposal: true,
  },
  {
    id: 6,
    status: "reflected",
    date: "2026.01.10",
    title: "현장 내 음수대 추가 설치 요청",
    content: "현장 내 음수대가 부족하여 근로자들이 불편을 겪고 있습니다.",
    authorInitial: "이",
    authorName: "이서연",
    isMyProposal: false,
  },
  {
    id: 7,
    status: "rejected",
    date: "2026.01.09",
    title: "안전모 보관함 추가 설치 요청",
    content: "현재 보관함 수량이 부족해 안전모가 바닥에 방치되는 경우가 많습니다.",
    authorInitial: "홍",
    authorName: "홍길동",
    isMyProposal: true,
  },
  {
    id: 8,
    status: "rejected",
    date: "2026.01.03",
    title: "창고 바닥 미끄럼 방지 패드 요청",
    content: "창고 입구 바닥이 비가 오면 매우 미끄럽습니다.",
    authorInitial: "최",
    authorName: "최성민",
    isMyProposal: false,
  },
]
