import type { HazardDetail } from "@/screens/HazardRiskScreen/types"

export const mockHazardDetails: Record<number, HazardDetail> = {
  1: {
    id: 1,
    status: "pending",
    date: "2026.05.18 14:32",
    location: "3층 계단실",
    description:
      "계단 난간 파손으로 추락 위험이 존재합니다. 3층 동측 계단 난간 2개소가 완전히 파손되어 있어, 지나가는 작업자의 낙상 사고 위험이 매우 높습니다. 즉각적인 조치가 필요합니다.",
    reporterName: "김철수",
    reporterInitial: "김",
    workplace: "광교타워크레인 현장",
    isMyReport: false,
    photos: [
      "https://picsum.photos/seed/hazard1a/400/300",
      "https://picsum.photos/seed/hazard1b/400/300",
    ],
    managerName: "김영희",
    managerInitial: "김",
    managerAffiliation: "안전관리팀",
    history: [{ id: 11, status: "pending", date: "2026.05.18 14:32" }],
  },
  2: {
    id: 2,
    status: "ongoing",
    date: "2026.05.16 09:15",
    location: "지하 1층 전기실",
    description:
      "배전반 문 잠금장치 불량으로 감전 위험이 존재합니다. 전기실 내 배전반 3호기의 문 잠금장치가 파손되어 아무나 접근 가능한 상태이며, 이로 인한 감전 사고 위험이 있습니다.",
    reporterName: "이영희",
    reporterInitial: "이",
    workplace: "광교타워크레인 현장",
    isMyReport: false,
    photos: ["https://picsum.photos/seed/hazard2a/400/300"],
    managerName: "박준호",
    managerInitial: "박",
    managerAffiliation: "시설관리팀",
    history: [
      { id: 21, status: "pending", date: "2026.05.16 09:15" },
      { id: 22, status: "ongoing", date: "2026.05.16 10:30" },
    ],
  },
  3: {
    id: 3,
    status: "completed",
    date: "2026.05.14 11:07",
    location: "옥상 작업장",
    description:
      "안전난간 미설치 구간이 발생하였습니다. 옥상 북측 작업구간 약 10m 구간에 안전난간이 설치되지 않아 추락 위험이 있습니다.",
    reporterName: "박민준",
    reporterInitial: "박",
    workplace: "수원역 복합개발 현장",
    isMyReport: false,
    photos: [],
    managerName: "최지현",
    managerInitial: "최",
    managerAffiliation: "안전관리팀",
    history: [
      { id: 31, status: "pending", date: "2026.05.14 11:07" },
      { id: 32, status: "ongoing", date: "2026.05.14 13:20" },
      {
        id: 33,
        status: "completed",
        date: "2026.05.15 15:45",
        note: "손잡이 재설치 완료 및 고정 상태 확인하였습니다.",
      },
    ],
  },
  4: {
    id: 4,
    status: "impossible",
    date: "2026.05.12 16:48",
    location: "2층 화장실",
    description:
      "바닥 미끄럼 방지 타일이 탈락되었습니다. 화장실 입구 부분 미끄럼방지 타일 3장이 탈락되어 바닥이 미끄러운 상태입니다.",
    reporterName: "최지원",
    reporterInitial: "최",
    workplace: "수원역 복합개발 현장",
    isMyReport: false,
    photos: [
      "https://picsum.photos/seed/hazard4a/400/300",
      "https://picsum.photos/seed/hazard4b/400/300",
      "https://picsum.photos/seed/hazard4c/400/300",
    ],
    managerName: "이수현",
    managerInitial: "이",
    managerAffiliation: "현장관리팀",
    history: [
      { id: 41, status: "pending", date: "2026.05.12 16:48" },
      { id: 42, status: "ongoing", date: "2026.05.13 09:00" },
      {
        id: 43,
        status: "impossible",
        date: "2026.05.13 11:30",
        note: "해당 타일 재고가 없어 현재 자재 주문 중입니다. 자재 입고 후 재시공 예정입니다.",
      },
    ],
  },
  5: {
    id: 5,
    status: "pending",
    date: "2026.05.10 08:53",
    location: "1층 로비",
    description:
      "비상구 앞 적재물 방치로 대피 경로가 차단되었습니다. 로비 비상구 인근에 건자재가 쌓여 있어 비상 시 대피에 지장이 있습니다.",
    reporterName: "정우성",
    reporterInitial: "정",
    workplace: "광교타워크레인 현장",
    isMyReport: false,
    photos: [],
    managerName: "김영희",
    managerInitial: "김",
    managerAffiliation: "안전관리팀",
    history: [{ id: 51, status: "pending", date: "2026.05.10 08:53" }],
  },
  6: {
    id: 6,
    status: "ongoing",
    date: "2026.05.08 13:20",
    location: "외벽 비계",
    description:
      "비계 연결 볼트 이완으로 구조가 불안정합니다. 외벽 비계 3단~5단 사이 연결 볼트 약 12개소가 이완되어 있으며, 구조 불안정으로 인한 붕괴 위험이 있습니다.",
    reporterName: "한수진",
    reporterInitial: "한",
    workplace: "수원역 복합개발 현장",
    isMyReport: false,
    photos: ["https://picsum.photos/seed/hazard6a/400/300"],
    managerName: "박준호",
    managerInitial: "박",
    managerAffiliation: "시설관리팀",
    history: [
      { id: 61, status: "pending", date: "2026.05.08 13:20" },
      { id: 62, status: "ongoing", date: "2026.05.09 14:00" },
    ],
  },

  // ── 본인 제보 테스트용 (isMyReport: true) — 상태별 4가지 ──────────────────
  // id: 7  → 대기중
  // id: 8  → 진행중  (근로자: "수정 불가" 안내 메시지)
  // id: 9  → 조치완료 (근로자+관리자: 결과 카드)
  // id: 10 → 조치불가 (근로자+관리자: 결과 카드)

  7: {
    id: 7,
    status: "pending",
    date: "2026.06.01 09:10",
    location: "4층 복도",
    description:
      "소화기 비치함 덮개가 파손되어 소화기가 외부에 노출되어 있습니다. 화재 시 신속한 사용에 지장이 있을 수 있습니다.",
    reporterName: "이민준",
    reporterInitial: "이",
    isMyReport: true,
    workplace: "광교타워크레인 현장",
    photos: ["https://picsum.photos/seed/hazard7a/400/300"],
    managerName: "김영희",
    managerInitial: "김",
    managerAffiliation: "안전관리팀",
    history: [{ id: 71, status: "pending", date: "2026.06.01 09:10" }],
  },
  8: {
    id: 8,
    status: "ongoing",
    date: "2026.05.30 14:22",
    location: "지하 주차장 입구",
    description:
      "차량 진출입 구간 바닥 도색이 마모되어 구분선이 불명확합니다. 보행자와 차량 동선이 겹쳐 충돌 위험이 있습니다.",
    reporterName: "이민준",
    reporterInitial: "이",
    isMyReport: true,
    workplace: "광교타워크레인 현장",
    photos: [
      "https://picsum.photos/seed/hazard8a/400/300",
      "https://picsum.photos/seed/hazard8b/400/300",
    ],
    managerName: "박준호",
    managerInitial: "박",
    managerAffiliation: "시설관리팀",
    history: [
      { id: 81, status: "pending", date: "2026.05.30 14:22" },
      { id: 82, status: "ongoing", date: "2026.05.31 09:00" },
    ],
  },
  9: {
    id: 9,
    status: "completed",
    date: "2026.05.28 10:05",
    location: "2층 창고",
    description:
      "선반 고정 볼트 이완으로 선반이 기울어져 있습니다. 무거운 자재가 적재되어 있어 낙하 사고 위험이 높습니다.",
    reporterName: "이민준",
    reporterInitial: "이",
    isMyReport: true,
    workplace: "수원역 복합개발 현장",
    photos: ["https://picsum.photos/seed/hazard9a/400/300"],
    managerName: "최지현",
    managerInitial: "최",
    managerAffiliation: "안전관리팀",
    history: [
      { id: 91, status: "pending", date: "2026.05.28 10:05" },
      { id: 92, status: "ongoing", date: "2026.05.28 13:30" },
      {
        id: 93,
        status: "completed",
        date: "2026.05.29 11:00",
        note: "선반 볼트 전체 재조임 및 과적 자재 재배치 완료하였습니다. 추가 점검 후 이상 없음을 확인하였습니다.",
      },
    ],
  },
  10: {
    id: 10,
    status: "impossible",
    date: "2026.05.25 16:40",
    location: "옥상 환기구",
    description:
      "환기구 덮개 부식으로 파손 위험이 있습니다. 장기간 방치로 인해 부식이 심화되어 덮개 일부가 들뜬 상태입니다.",
    reporterName: "이민준",
    reporterInitial: "이",
    isMyReport: true,
    workplace: "수원역 복합개발 현장",
    photos: [
      "https://picsum.photos/seed/hazard10a/400/300",
      "https://picsum.photos/seed/hazard10b/400/300",
    ],
    managerName: "이수현",
    managerInitial: "이",
    managerAffiliation: "현장관리팀",
    history: [
      { id: 101, status: "pending", date: "2026.05.25 16:40" },
      { id: 102, status: "ongoing", date: "2026.05.26 10:00" },
      {
        id: 103,
        status: "impossible",
        date: "2026.05.27 15:20",
        note: "제조사 단종 부품으로 교체가 불가합니다. 건물 노후화로 전면 교체 공사가 필요하며, 예산 협의 후 장기 계획에 반영 예정입니다.",
      },
    ],
  },
}
