import { TbmItem } from "./types"

export const mockTbmData: TbmItem[] = [
  {
    id: 1,
    title: "작업장 순회 점검",
    status: "진행중",
    date: "2026.02.19",
    participants: 4,
    author: "권 민수 사업장 관리자",
    location: "서울 영등포구 레미안스 비즈타워 8층",
  },
  {
    id: 2,
    title: "작업장 순회 점검",
    status: "종료됨",
    date: "2026.02.19",
    participants: 3,
    author: "권 민수 사업장 관리자",
    location: "서울 영등포구 레미안스 비즈타워 3층",
  },
  {
    id: 3,
    title: "전기설비 안전점검",
    status: "진행중",
    date: "2026.02.18",
    participants: 2,
    author: "김 영호 안전관리자",
    location: "부산 해운대구 센텀시티 12층",
  },
  {
    id: 4,
    title: "고소작업 안전교육",
    status: "종료됨",
    date: "2026.02.17",
    participants: 8,
    author: "이 정민 현장소장",
    location: "인천 연수구 송도동 건설현장",
  },
  {
    id: 5,
    title: "화학물질 취급 안전점검",
    status: "진행중",
    date: "2026.02.16",
    participants: 5,
    author: "박 서연 환경안전팀장",
    location: "경기 화성시 동탄산업단지 A동",
  },
  {
    id: 6,
    title: "비계 설치 작업 전 TBM",
    status: "종료됨",
    date: "2026.02.15",
    participants: 6,
    author: "최 준혁 현장안전팀장",
    location: "대구 달서구 성서산업단지 3공장",
  },
  {
    id: 7,
    title: "크레인 작업 안전교육",
    status: "진행중",
    date: "2026.02.14",
    participants: 3,
    author: "정 수진 안전관리자",
    location: "경남 창원시 성산구 가음정동",
  },
  {
    id: 8,
    title: "밀폐공간 작업 전 TBM",
    status: "종료됨",
    date: "2026.02.13",
    participants: 4,
    author: "한 동현 현장소장",
    location: "울산 남구 여천동 석유화학단지",
  },
  {
    id: 9,
    title: "용접 작업 안전점검",
    status: "종료됨",
    date: "2026.02.12",
    participants: 2,
    author: "윤 지훈 안전관리자",
    location: "충북 청주시 흥덕구 오창읍",
  },
  {
    id: 10,
    title: "굴삭기 작업 TBM",
    status: "진행중",
    date: "2026.02.11",
    participants: 5,
    author: "임 채원 현장안전팀장",
    location: "전남 광양시 금호동 제철소 구역",
  },
]
